### ISSUE TITLE
add requirements.txt

### ISSUE THREAD

**Issue by rdaumann** [0xfederama/connection-analyzer#1]
write down the dependencies in a `requirements.txt` the project uses, such that others can install them with `pip`.

**Comment by 0xfederama** [comment]
I've written that in the readme, what's the point of creating/using a txt file for the dependencies? Genuinely asking

**Comment by rdaumann** [comment]
The requirements file also contains the used version of your libraries. A newer version could break your program.

**Comment by 0xfederama** [comment]
I changed the pip command to install the specific version of the library, even if the latest release of speedtest-cli is from 2019 and I don't think they're gonna release a newer one
